export const PageViewSelectors = {
  PageRoot: '.Root__main-view .main-view-container div[data-overlayscrollbars-viewport]',
  AmaiLyricsPage: '#AmaiLyricsPage',
  ContentBox: '#AmaiLyricsPage .ContentBox',
  MediaImage: '#AmaiLyricsPage .MediaImage',
  SongName: '#AmaiLyricsPage .SongName span',
  Artists: '#AmaiLyricsPage .Artists span',
  ViewControls: '#AmaiLyricsPage .ContentBox .ViewControls',
  Header: '#AmaiLyricsPage .ContentBox .NowBar .Header',
  HeaderViewControls: '#AmaiLyricsPage .ContentBox .NowBar .Header .ViewControls',
  RefreshLyricsButton: '#RefreshLyrics',
  WatchMusicVideoButton: '#WatchMusicVideoButton',
  SettingsButton: '#AmaiSettingsButton',
  ActionButtonContainer: '#AmaiLyricsPage .ContentBox .NowBar .AmaiPageButtonContainer',
  CloseButton: '#Close',
  FullscreenToggleButton: '#FullscreenToggle',
  LoaderContainer: '#AmaiLyricsPage .loaderContainer',
  LyricsContent: '#AmaiLyricsPage .LyricsContent',
  NowBar: '#AmaiLyricsPage .NowBar',
  NotificationContainer: '#AmaiLyricsPage .NotificationContainer',
};
